server:
  port: 8080

application:
  esp:
    storagePathFw: storage/esp/frw
    storagePathFs: storage/esp/fs
    prefFw: firmware_
    prefFs: spiffs_
springdoc:
  swagger-ui:
    url: /swagger/swagger-main.yaml
